### PR TITLE
Adding ability to output numbers

### PR DESCRIPTION
**Pull request by superbeefy**

### CODE REVIEW

**Comment by mlmorg** [comment]
Just wrap in a string?

```
r.p('5000');
```

**Comment by superbeefy** [comment]
That works for a literal string, but if your dealing with number in a var or JSON you'd have to call obj.number.toString(). I don't think you should have to do that.

If we didn't want to support number types, it fails silently. At the minimum we should have a console.warn message about invalid types.

**Comment by mlmorg** [comment]
Ok. Can we add a test for it? Thanks!

**Comment by mlmorg** [comment]
Published as `v1.3.0`

**Pull request merged**
