### PR TITLE
Move react to peerDependencies

### LINKED ISSUE #15: Move react to peerDependencies
Browserified bundles double-up on react instances, even for semver-comatible things.

cc @ross-

### PR DESCRIPTION
**Pull request by lxe**
Fix #15

### CODE REVIEW

**Comment by lxe** [comment]
Totally missed https://github.com/uber/r-dom/pull/14

**Comment by Raynos** [comment]
@lxe consider `npm dedupe`

**Comment by lxe** [comment]
@Raynos did that, but no avail :( I think npm dedupe doesn't play well if there are git+ssh deps in the tree

**Comment by lxe** [comment]
@Raynos npm dedupe fails for whatever reason :(

```
npm WARN unavoidable conflict Not de-duplicating
npm WARN unavoidable conflict react { '/Users/aleksey/devel/.../node_modules/r-dom/node_modules/react': '0.12.2',
npm WARN unavoidable conflict   '/Users/aleksey/devel/.../node_modules/react': '0.12.1' }
```

**Pull request closed without merging**
